### PR TITLE
Use more inclusive language and require xdist >=1.22.3

### LINKED ISSUE #43: Upcoming incompatibility in pytest-xdist 2.0: "slave" aliases removed
Hi!

As per https://github.com/pytest-dev/pytest-xdist/pull/541, pytest-xdist 2.0 will remove the deprecated "slave" 
aliases, which have been replaced by "worker" since pytest-xdist 1.22.

To avoid breakage, the team suggests to update your package to use the new terms, and make a new release to avoid sudden breakages once pytest-xdist 2.0 is released.

cc @Zac-HD @RonnyPfannschmidt

Thanks!

### PR DESCRIPTION
**Pull request by asottile**
Resolves #43

### CODE REVIEW

**Comment by asottile** [comment]
I opted for removing support for older xdist for simplicity sake -- I could adjust this patch such that it produces a warning / error instead?  what are your thoughts on this

**Comment by Zac-HD** [comment]
`xdist` made this change in 2017, so IMO breaking compatibility with older versions is fine - that's certainly my plan for the other plugins!

**Comment by Zac-HD** [comment]
@tonybaloney - FYI we expect to release `pytest-xdist` 2.0 this week, and `pytest-nunit` will be incompatible without this change.

**Comment by asottile** [comment]
I'll handle this, I think I have enough access to merge and deploy this -- first I'm going to try and get CI working again

**Pull request merged**
